from .province_form import ProvinceForm
from .commune_form import CommuneForm
from .zone_form import ZoneForm
from .utilisateur_form import UtilisateurForm
from .exetat_form import ExetatForm
from .cours_form import CoursForm
from .section_form import SectionForm
from .cours_sections_form import CoursSectionForm
from .utilisateur_role_form import UserEditForm
from .etudiant_form import EtudiantForm
from .laureat_form import LaureatForm
from .rendez_vous_form import Rendez_vousForm