# Generated by Django 4.2.2 on 2023-07-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendez_vous',
            name='code',
        ),
    ]
