from .province import *
from .commune import *
from .zone import *
from .etudiant import *
from .cours import *
from .section import *
from .section_cours import *
from .exetat import *
from .laureat import *
from .rendez_vous import *
from .user import *