from .home import *
from .admin import *
from .agent_de_saisie import *
from .organisateur import *
from .receptioniste import *
from .provinces import *
from .communes import *
from .zones import *
from .utilisateurs import *
from .exetats import *
from .cours import *
from .sections import *
from .cours_sections import *
from .etudiants import *
from .laureats import *
from .demandes import *
from .public import *
from .mailsend import *
from .qrcode import *